sudo: required
services:
- docker
language: bash
branches:
  only:
  - master
script:
- |
  echo "Updating Docker to have docker manifest command"
  curl https://get.docker.com | sh
  echo "Enabling docker client experimental features"
  mkdir -p ~/.docker
  echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  docker version
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# build image
- docker build --build-arg distro=stretch -t haegi/silex-dashboard .
# test image

# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV SILEX_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag haegi/silex-dashboard haegi/silex-dashboard:arm-$TAG
    docker push haegi/silex-dashboard:arm-$TAG
    docker manifest create haegi/silex-dashboard:$TAG haegi/silex-dashboard:arm-$TAG
    docker manifest annotate haegi/silex-dashboard:$TAG haegi/silex-dashboard:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push haegi/silex-dashboard:$TAG
    docker manifest create haegi/silex-dashboard haegi/silex-dashboard:arm-$TAG
    docker manifest annotate haegi/silex-dashboard haegi/silex-dashboard:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push haegi/silex-dashboard
  fi